<?php
/**
 * @file
 *
 */

 /**
  * Implements hook_help().
  */
 function custom_module_help($path, $arg) {
   switch ($path) {
     case 'admin/help#custom_module':{
       $ret_val = '<h3>' . t('About') . '</h3>';
       $ret_val .= '<p>' . t('Custom Module.') . '</p>';
       return $ret_val;
       break;
     }
   }
 }
 /**
  * Implements hook_permission().
  */
 function custom_module_permission() {
   return array(
     'Custom Module Drupal 7' => array(
       'title' => t('Custom Module'),
       'description' => t('Custom Module in Drupal 7.'),
     ),
   );
 }

 /**
  * Implements hook_menu().
  */
 function custom_module_menu() {
   $items = array();

   // Admin configuration group.
   $items['admin/config/custom_module'] = array(
     'title' => 'Custom Module',
     'description' => 'Administer Custom Module in Drupal 7.',
     'access arguments' => array('administer Custom Module'),
   );

   // Admin configuration - Settings.
   $items['admin/config/custom_module/manage'] = array(
     'title' => 'Custom Module settings',
     'description' => 'Manage Custom Module settings and configurations.',
     'access arguments' => array('administer Custom Module'),
     'page callback' => 'drupal_get_form',
     'page arguments' => array('custom_module_admin_settings_form'),
   );

   return $items;
 }


 /**
  * Implements hook_form().
  */
 function custom_module_admin_settings_form($node, &$form_state) {
   $form = array();

   $form['overview'] = array(
     '#markup' => t('This interface allows administrators to manage general Custom Module Settings'),
     '#prefix' => '<p>',
     '#suffix' => '</p>',
   );

   $form['custom_module_gmap'] = array(
     '#title' => t('Enable Google Maps'),
     '#description' => t('When enabled, Google Maps will be rendered if latitude and longitude are known.'),
     '#type' => 'checkbox',
     '#default_value' => 1,
   );

   $form['default_center'] = array(
     '#title' => t('Map Center'),
     '#description' => t('Location of the center of the map of wind farms.'),
     '#type' => 'fieldset',
     '#collapsible' => TRUE,
     '#collapsed' => FALSE,
   );

   $form['default_center']['custom_module_default_center_lat'] = array(
     '#title' => t('Latitude'),
     '#description' => t('Signed degrees format (DDD.dddd)'),
     '#type' => 'textfield',
     '#default_value' => 42.91455,
     '#required' => TRUE,
   );

   $form['default_center']['custom_module_default_center_long'] = array(
     '#title' => t('Longitude'),
     '#description' => t('Signed degrees format (DDD.dddd)'),
     '#type' => 'textfield',
     '#default_value' => -75.569851,
     '#required' => TRUE,
   );

   $options = range(0, 20, 1);
   $options[0] = t('0 - Furthest');
   $options[20] = t('20 - Closest');

   $form['custom_module_default_gmap_zoom'] = array(
     '#title' => t('Google Map zoom'),
     '#description' => t('Default level of zoom, between 0 and 20.'),
     '#type' => 'select',
     '#options' => $options,
     '#default_value' => 8,
     '#required' => TRUE,
   );

   $form['submit'] = array(
     '#type' => 'submit',
     '#value' => t('Save'),
   );

   return $form;
 }
